health_checks:
  - name: "check_repo_clone"
    description: standard repository checks (clone, push, PR)
    type: "repo"
    severity: "critical"
    message: "This is a custom message"
    params:
      repo: "https://github.com/jefeish/test-health-check.git" # required: repository name
      branch: "" # optional: default is "main"

  - name: "check_repo_commit"
    description: standard repository checks (clone, push, PR)
    type: "repo"
    severity: "medium"
    message: "This is a custom message"
    params:
      repo: "https://github.com/jefeish/test-health-check.git" # required: repository name
      branch: "" # optional: default is "main"

  - name: "check_repo_pr_open"
    description: standard repository checks (clone, push, PR)
    type: "repo"
    severity: "low"
    message: "This is a custom message"
    params:
      repo: "https://github.com/jefeish/test-health-check.git" # required: repository name
      branch: "" # optional: default is "main"

  - name: "check_repo_pr_close"
    description: standard repository checks (clone, push, PR)
    type: "repo"
    severity: "high"
    message: "This is a custom message"
    params:
      repo: "https://github.com/jefeish/test-health-check.git" # required: repository name
      branch: "" # optional: default is "main"

reports:
  - name: "markdownReportIssue"
    description: "Markdown report issue"

  - name: "markdownReportFile"
    description: "Markdown report"
    params:
      path: "./reports/report.md"
      
  - name: "csvReportFile"
    description: "CSV report"
    params:
      path: "./reports/report.csv"   

  # - name: "jsonReportFile"
  #   description: "JSON report"
  #   params:
  #     path: "./reports/report.json"
