logger:
  level: info
globals:
  overwrite: false
  params:
    repo: 'https://github.com/jefeish/test-health-check.git'
    branch: jefeish/patch-1
    owner: jefeish
health_checks:
  - name: check_repo_clone
    description: standard repository checks (clone)
    type: repo
    severity: critical
    message: This is a custom message
    params:
      repo: 'https://github.com/jefeish/test-health-check.git'
      branch: ''
      target: /tmp
  - name: check_repo_commit
    description: 'standard repository checks (clone, commit, push)'
    type: repo
    severity: critical
    message: This is a custom message
    params:
      repo: 'https://github.com/jefeish/test-health-check.git'
      branch: main
      target: /tmp
  - name: check_repo_pr_open
    description: 'standard repository checks (clone, branch, commit, push, open PR)'
    type: repo
    severity: high
    message: This is a PR health check
    params:
      repo: 'https://github.com/jefeish/test-health-check.git'
      branch: jefeish/patch-1
      target: /tmp
  - name: check_repo_pr_close
    description: standard repository checks (close PR)
    type: repo
    severity: high
    message: This is a custom message
    params:
      repo: 'https://github.com/jefeish/test-health-check.git'
      branch: jefeish/patch-1
  - name: check_issue_create
    description: standard Issue checks (open issue)
    type: issue
    severity: low
    message: This is a custom message
    params:
      repo: test-health-check
  - name: check_issue_comment
    description: standard Issue checks (comment issue)
    type: issue
    severity: low
    message: This is a custom message
    params:
      repo: test-health-check
  - name: check_issue_close
    description: standard Issue checks (close issue)
    type: issue
    severity: low
    message: This is a custom message
    params:
      repo: test-health-check
  - name: check_url_endpoint
    description: 'check the URL endpoint: https://copilot-proxy.githubusercontent.com/_ping'
    type: endpoint
    severity: low
    message: Testing URL
    params:
      url: 'https://copilot-proxy.githubusercontent.com/_ping'
reports:
  - name: markdownReportIssue
    description: Markdown report issue
  - name: markdownReportFile
    description: Markdown report
    params:
      path: ./reports/report.md
  - name: csvReportFile
    description: CSV report
    params:
      path: ./reports/report.csv
  - name: jsonReportFile
    description: JSON report
    params:
      path: ./reports/report.json
